### ISSUE TITLE
What are the specific label IDs used in the PanNuke dataset masks?

### ISSUE THREAD

**Issue by li-qi-lin** [microsoft/BiomedParse#35]
I am working with the **PanNuke** dataset and trying to understand the label IDs used in the masks. Could you provide clarification on what each label ID corresponds to in the dataset's masks?

**Comment by li-qi-lin** [comment]
Are PanNuke and GlaS the only pathology datasets used? Why are there more pathology data mentioned in the paper?

**Comment by theodore-zhao** [comment]
All mask corresponds to the name of the target. The targets in our processed datasets are: neoplastic cells, epithelial cells, inflammatory cells, connective tissue cells. If you are working on the original version of PanNuke, you can find in the description to match the target names to the ID number.
PanNuke and GlaS are the datasets used for model training and evaluation. We curated on additional pathology dataset, but due to data size and quality we didn't use that for model development, which was described in Supp Table 1. We are currently holding those per request.

**Comment by li-qi-lin** [comment]
The PanNuke dataset webpage is currently inaccessible. Is there any alternative source for the dataset description?

**Comment by theodore-zhao** [comment]
You can check out this one. https://www.kaggle.com/datasets/andrewmvd/cancer-inst-segmentation-and-classification

**Comment by theodore-zhao** [comment]
We processed the dataset from https://www.kaggle.com/datasets/andrewmvd/cancer-inst-segmentation-and-classification, together with Part 2 and 3. The label IDs corresponding to each class are: {0: 'Neoplastic cells', 1: 'Inflammatory', 2: 'Connective/Soft tissue cells', 3: 'Dead Cells', 4: 'Epithelial'}. We used all the images from the source dataset but the dead cell annotations.

Hope this helps!

**Comment by li-qi-lin** [comment]
Have you merged the labels of the oriHave you merged the labels of the original PanNuke dataset? Is the released data the processed complete dataset or just a part of it?ginal PanNuke dataset? Is the released data the processed complete dataset or just a part of it?

Thank you!

**Comment by theodore-zhao** [comment]
We processed the full dataset from the Kaggle version.

**Comment by li-qi-lin** [comment]
Is the PanNuke dataset released in your repository the processed version of all the data, or is it only a portion of the processed data?

Thank you！

**Comment by theodore-zhao** [comment]
It is the processed version of all the data.
