### ISSUE TITLE
Issue with identifying Lung X-ray Pathologies

### ISSUE THREAD

**Issue by arvindmvepa** [microsoft/BiomedParse#36]
Hello,

I tried to modify example_prediction.py to get masks for lung X-ray images for common lung pathologies (Atelectasis, Cardiomegaly, Effusion, Infiltration, Mass, Nodule, Pneumonia, Pneumothorax, Consolidation, Edema, Emphysema, Fibrosis, Pleural Thickening and Hernia) and I found that the model tends to over-diagnose pathologies as well as predict identical masks for multiple pathologies. Do you have any idea what the issue is?

Thanks,

Arvind

**Comment by theodore-zhao** [comment]
Hi Arvind,

Due to lack of high quality segmentation annotations for lung pathologies in X-Ray, the model was not trained on most of these conditions. We provided a list of evaluated segmentation object types on the model card page. If you have any annotated data on segmentation of these pathologies, you can finetune the model on them. 

Best,
Theo

**Comment by arvindmvepa** [comment]
Got it. Thank you!
